stages:
  - build_backend
  - deploy_backend

variables:
  JAVA_VERSION: "17"
  JAR_PATH: "${BACKEND_DIR}/build/libs"
  JAR_NAME: "your-backend.jar"

build_backend_job:
  stage: build_backend
  image: openjdk:${JAVA_VERSION}-jdk-slim
  script:
    - cd ${BACKEND_DIR}
    - chmod +x gradlew
    - ./gradlew clean build -x test
  artifacts:
    paths:
      - ${JAR_PATH}/*.jar
    expire_in: 1 day
  only:
    - master
  tags:
    - master

deploy_backend_job:
  stage: deploy
  image: ubuntu:latest
  before_script:
    - apt update && apt install -y openssh-client --no-install-recommends
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa_ci
    - chmod 600 ~/.ssh/id_rsa_ci
    - ssh-add ~/.ssh/id_rsa_ci
    - echo "Host *" > ~/.ssh/config
    - echo "    StrictHostKeyChecking no" >> ~/.ssh/config
    - echo "    UserKnownHostsFile /dev/null" >> ~/.ssh/config
  script:
    - JAR_SOURCE_PATH=$(find ${JAR_PATH}/ -name "*.jar" ! -name "*-plain.jar")
    - echo "Deploying JAR ${JAR_SOURCE_PATH} to ${SERVER_HOST}:/home/${SERVER_USER}/${JAR_NAME}"
    - scp "${JAR_SOURCE_PATH}" ${SERVER_USER}@${SERVER_HOST}:/home/${SERVER_USER}/${JAR_NAME}
    - |
      ssh -v -o ConnectTimeout=10 -o ServerAliveInterval=15 ${SERVER_USER}@${SERVER_HOST} "\
      set -e; \
      echo 'Attempting to kill existing process...'; \
      sudo /usr/bin/pkill -f '${JAR_NAME}' || { echo 'pkill failed or no process found.'; }; \
      sudo /usr/bin/fuser -k 8080/tcp || { echo 'fuser failed or no process on 8080.'; }; \
      echo 'Starting new application process...'; \
      setsid nohup sudo /usr/bin/java -jar /home/${SERVER_USER}/${JAR_NAME} \
        --spring.datasource.username=${DB_USERNAME} \
        --spring.datasource.password=${DB_PASSWORD} \
        --spring.datasource.url=\"${DB_URL}\" \
        --spring.profiles.active=secret \
        # --spring.data.redis.host=${REDIS_HOST} \
        # --spring.data.redis.port=${REDIS_PORT} \
        # --spring.data.redis.password=${REDIS_PASSWORD} \
        > /home/${SERVER_USER}/your-backend.log 2>&1 < /dev/null & \
      \
      sleep 10; \
      \
      echo 'Application started command sent successfully (check log file for details).'; \
      " || { echo "SSH command itself failed with exit code $?"; exit 1; }
  after_script:
    - rm ~/.ssh/id_rsa_ci