spring:
  application:
    name: argo-backend

  profiles:
    include: secret

  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 30 # JDBC Batch 처리 사이즈
        order_inserts: true # INSERT 쿼리 최적화
        order_updates: true # UPDATE 쿼리 최적화

  data:
    redis:
      host: 172.19.64.149
      port: 6379

  # 포즈 판정 연동 : 인코딩 & 파일 업로드 설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    mvc:
      servlet:
        path: /
    multipart:
      enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: ${java.io.tmpdir}
      file-size-threshold: 1MB

# AI API 설정
python:
  api:
    base-url: http://localhost:8000

# FCM 설정
fcm:
  service-account-file: classpath:firebase/argo-80fe8-firebase-adminsdk-fbsvc-4494955e54.json
  project-id: "argo-80fe8"

# 로깅 설정 (개발용 유지)
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.argo.backend: DEBUG
