spring:
  application:
    name: argo-backend

  config:
    import: optional:application-secret.yml   # 항상 불러오기

  profiles:
    active: local  # 필요하면 명시, 아니면 이 줄 빼도 됨

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
      location: ${java.io.tmpdir}
      file-size-threshold: 1MB

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    mvc:
      servlet:
        path: /
    multipart:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.argo.backend: DEBUG